name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - { COMPILER: "gcc",   COMPILER_VERSION: "10" }
          - { COMPILER: "gcc",   COMPILER_VERSION: "11" }
          - { COMPILER: "clang", COMPILER_VERSION: "11" }
          - { COMPILER: "clang", COMPILER_VERSION: "12" }
          - { COMPILER: "clang", COMPILER_VERSION: "13" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Build check (${{ env.COMPILER }}-${{ env.COMPILER_VERSION }})
        run: sudo -E .github/workflows/build_test.sh
